import 'generation_request.dart';
import 'generation_result.dart';
import 'generator_registry.dart';

class FlutterGenerator extends BaseGenerator {
  @override
  Future<List<GeneratedFile>> generate(GenerationRequest request) async {
    return [
      GeneratedFile(
        path: 'lib/main.dart',
        content: '''
import 'package:flutter/material.dart';

void main() {
  runApp(const RaonsonApp());
}

class RaonsonApp extends StatelessWidget {
  const RaonsonApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(child: Text('Raonson')),
      ),
    );
  }
}
''',
      ),
      GeneratedFile(
        path: 'pubspec.yaml',
        content: '''
name: ${request.projectName.toLowerCase()}
description: Generated by King AI
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
''',
      ),
    ];
  }
}