class GeneratorTemplates {
  static List<Map<String, String>> appTemplate(String prompt) {
    return [
      {
        "path": "lib/main.dart",
        "content": "// Auto-generated App\n// Prompt: $prompt\nvoid main() {}"
      },
      {
        "path": "lib/app/app.dart",
        "content": "// App shell generated by King AI"
      },
    ];
  }

  static List<Map<String, String>> gameTemplate(String prompt) {
    return [
      {
        "path": "lib/game/game_engine.dart",
        "content": "// Game engine logic\n// $prompt"
      },
      {
        "path": "lib/game/game_ui.dart",
        "content": "// Game UI layer"
      },
    ];
  }

  static List<Map<String, String>> backendTemplate(String prompt) {
    return [
      {
        "path": "lib/backend/api.dart",
        "content": "// Backend API generated\n// $prompt"
      }
    ];
  }
}