import 'dart:async';
import 'dart:math';

import 'progress_tracker.dart';

class GeneratedFile {
  final String path;
  final String content;

  GeneratedFile({
    required this.path,
    required this.content,
  });
}

typedef FileWriter = Future<void> Function(GeneratedFile file);

class FileBatchGenerator {
  final int totalFiles;
  final int batchSize;
  final ProgressTracker progress;
  final FileWriter writer;

  final List<GeneratedFile> _queue = [];

  FileBatchGenerator({
    required this.totalFiles,
    required this.batchSize,
    required this.progress,
    required this.writer,
  });

  /// Entry point
  Future<void> generate() async {
    progress.start();

    int generated = 0;
    while (generated < totalFiles) {
      final remaining = totalFiles - generated;
      final currentBatch = min(batchSize, remaining);

      _queue.clear();
      for (int i = 0; i < currentBatch; i++) {
        _queue.add(_generateSingleFile(generated + i));
      }

      await _writeBatch(_queue);

      generated += currentBatch;

      progress.stepCompleted(
        generatedFiles: currentBatch,
      );
    }

    progress.complete();
  }

  GeneratedFile _generateSingleFile(int index) {
    final featureIndex = index % 7;

    final folder = switch (featureIndex) {
      0 => 'ui',
      1 => 'state',
      2 => 'services',
      3 => 'models',
      4 => 'controllers',
      5 => 'generators',
      _ => 'utils',
    };

    final fileName = 'generated_$index.dart';

    return GeneratedFile(
      path: 'lib/$folder/$fileName',
      content: _generateFileContent(index, folder),
    );
  }

  String _generateFileContent(int index, String folder) {
    return '''
// AUTO-GENERATED BY KING AI
// File index: $index
// Layer: $folder

class GeneratedFeature$index {
  String get name => "Feature $index";

  void execute() {
    print("Running feature $index from $folder");
  }
}
''';
  }

  Future<void> _writeBatch(List<GeneratedFile> files) async {
    for (final file in files) {
      await writer(file);
    }
  }
}
